### ISSUE TITLE
App registry not ready with Django 1.9

### ISSUE THREAD

**Issue by fellipeh** [django-erp/django-erp#24] opened 2016-01-04 19:44 UTC
I try to execute migrate, and get these error:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fellipeh/Developer/django-erp/djangoerp/pluggets/apps.py", line 23, in <module>
    from .loading import registry
  File "/Users/fellipeh/Developer/django-erp/djangoerp/pluggets/loading.py", line 22, in <module>
    from djangoerp.core.cache import Singleton
  File "/Users/fellipeh/Developer/django-erp/djangoerp/core/cache.py", line 21, in <module>
    from django.contrib.auth.models import AnonymousUser
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/fellipeh/.virtualenvs/djangoerp/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

I follow all steps, and copy base.py

**Comment by zuck** [comment] 2016-01-07 14:10
Are you using Python 3?

**Comment by luisza** [comment] 2016-01-08 16:11
No, he is not using python3, see his environment  "~/.virtualenvs/djangoerp/lib/python2.7/...".

**Comment by zuck** [comment] 2016-01-09 12:34
You're right, too hurry in answering, sorry ;)

BTW, according to what reported in #9 and to my tests, it seems the issue is with Django 1.9.

Could you @fellipeh confirm that?

**Comment by Samrat020292** [comment] 2019-08-19 14:48
raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by zuck** [comment] 2020-08-24 21:37
Should be fixed now

**Closed by zuck** 2020-08-24 21:37 UTC
